apiVersion: v1
kind: Service
metadata:
  name: mynode-client-service
spec:
  selector:
    name: mynode-client
  type: LoadBalancer  
  ports:
  - port: 3000
    targetPort: 3000
    # nodePort: 30002