apiVersion: v1
kind: Service
metadata:
  name: keycloak-development
spec:
  selector:
    name: keycloak-development
  type: ClusterIP  
  ports:
  - port: 8080
    targetPort: 8080
    # nodePort: 30002