apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynode-app-deployment
  labels:
    name: mynode-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: mynode-app
  template:
    metadata:
      labels:
        name: mynode-app
    spec:
      containers:
      - name: mynode-app-con
        image: vforvalient/mymongo-crud:0.0.8.RELEASE
        ports:
        - containerPort: 5000